# Generated by Django 3.1.1 on 2020-09-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
