# Generated by Django 3.1.1 on 2020-09-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200910_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
