# Generated by Django 3.1.1 on 2020-09-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
